# Generated by Django 4.1 on 2022-09-07 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_details', models.CharField(max_length=10000)),
                ('uses_vm', models.BooleanField()),
                ('uses_md', models.BooleanField()),
                ('terminal1', models.CharField(max_length=50)),
                ('terminal2', models.CharField(max_length=50)),
                ('terminal3', models.CharField(max_length=50)),
                ('terminal4', models.CharField(max_length=50)),
                ('custom_text', models.CharField(max_length=10000)),
                ('lab_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.labmodule')),
            ],
        ),
        migrations.CreateModel(
            name='LabTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('ND', 'Not Done'), ('F', 'Failure'), ('S', 'Success')], default='ND', max_length=2)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.labtask')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
