# Generated by Django 4.1.5 on 2023-01-03 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_labmodule_labtask_labtaskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_tile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_title', models.CharField(max_length=100)),
                ('lab_status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='labmodule',
            name='lab',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group'),
        ),
    ]
