# Generated by Django 4.1 on 2022-09-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_labtask_task_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='custom_text',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtask',
            name='terminal1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtask',
            name='terminal2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtask',
            name='terminal3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtask',
            name='terminal4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtask',
            name='uses_md',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtask',
            name='uses_vm',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
