# Generated by Django 4.1 on 2022-08-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_status', models.CharField(choices=[('ND', 'Not Done'), ('F', 'Failure'), ('S', 'Success')], default='ND', max_length=2)),
                ('lab_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.labmodule')),
            ],
        ),
    ]
