# Generated by Django 4.1 on 2022-09-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='task_details',
            field=models.CharField(default=123, max_length=10000),
            preserve_default=False,
        ),
    ]
